name = "nishiweb"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# This is the key property for Pages
pages_build_output_dir = ".vercel/output/static"

# Optional: specify build command (though Pages usually handles this)
[build]
command = "npx @cloudflare/next-on-pages@1"